default: &default
  adapter: sqlite3
  pool: 5
  timeout: 5000

development:
  <<: *default
  adapter: postgresql
  encoding: unicode
  pool: 5

test:
  <<: *default
  database: db/test.sqlite3

production:
  <<: *default
  database: db/production.sqlite3
